### ISSUE TITLE
3장까지 공부 진행 및 4장 추가 진행 .. etc

### ISSUE THREAD

**Issue by loustler** [codechobostudy/study-dev-scala#10]
@audtjddld @loustler 
3장 마저 진행
@m-s-k 4장까지 추가 진행

스터디 추가 진행 여부 결정
최초 진행 예정인 1달이 만료됨

**Comment by audtjddld** [comment]
열심히 해야되는데 =_=;;

**Comment by loustler** [comment]
이번주는 개인적인 사정과 미흡한 준비상태로 인해 
오프라인 만남은 하지 않고,
진행한 부분은 **PR**

또, 스터디 진행여부에 대해 의견조율이 필요함 

@audtjddld님, @m-s-k 님 
스터디 기획시 계획했던 스터디 진행기간이 이번주 토요일인 12/3(토)로 끝입니다.
추가 진행을 하실 건지에 대해 **comment** 남겨주세요

**Comment by loustler** [comment]
추가 진행 협의 완료
